### ISSUE TITLE
Remove dependency on pkl binary

### ISSUE THREAD

**Issue by udf2457** [apple/pkl-go#20]
The docs (https://pkl-lang.org/go/current/evaluation.html#without-code-generation) appear to imply that Go should be able to parse pkl files natively.

However `pkl.NewEvaluator` appears to have a dependency on the `pkl` binary being present, because `pkl.NewEvaluator(context.Background(), pkl.PreconfiguredOptions)` on a system with no `pkl` binary returns `exec: "pkl": executable file not found in $PATH`

**Comment by bioball** [comment]
The documentation is saying that you can use pkl-go without code generation, which is what `pkl-gen-go` provides for you.

However, `pkl` is still required as a system dependency. This is because, unlike TOML, YAML, or JSON, Pkl files are programs that need to be evaluated in order to produce a result.

In the future, we will also provide a C library, which will remove the need to shell out to a child process.
