### ISSUE TITLE
`pkl-gen-go` doesn't generate Go code for an imported module

### ISSUE THREAD

**Issue by gsom95** [apple/pkl-go#61]
I'm new to the pkl and pkl-gen-go and maybe I'm missing something.

# What are/were you trying to achieve?
There are 2 config files:

1. Contains some fields
```pkl
@go.Package { name = "awesome/pkg/gen/httpserver" }
module exp.HttpServer

import "package://pkg.pkl-lang.org/pkl-go/pkl.golang@0.6.0#/go.pkl"

host: String(!isEmpty) = "localhost"

typealias Port = UInt16
port: Port = 8080

typealias TimeoutDuration = Duration

class Timeouts {
  readTO: TimeoutDuration = 10.s
  writeTO: TimeoutDuration = 10.s
}

timeouts: Timeouts
```

2. Imports the first files/modules and creates a new object
```pkl
@go.Package { name = "awesome/pkg/gen/config" }
module exp.MainConfig

import "package://pkg.pkl-lang.org/pkl-go/pkl.golang@0.6.0#/go.pkl"
import "HttpServer.pkl"

server = new HttpServer {
  port = 7000
}
```

If I try to generate Go files with `pkl-gen-go pkl/MainConfig.pkl`, I would only get files for the `MainConfig` and no files for `HttpServer`.

In addition, the generated struct will have `any` type for the `Server`  field in the `MainConfig`:

```go
type MainConfig struct {
	Server any `pkl:"server"`
}
```

---

But if I annotate `server` in `MainConfig` with `HttpServer`, the `pkl-gen-go` would create all the files:
```pkl
@go.Package { name = "github.com/gsom95/go-pkl/gen/config" }
module exp.MainConfig

import "package://pkg.pkl-lang.org/pkl-go/pkl.golang@0.6.0#/go.pkl"
import "HttpServer.pkl"

server: HttpServer = new HttpServer {
  port = 7000
}
```

Go generated struct:
```go
type MainConfig struct {
	Server *httpserver.HttpServer `pkl:"server"`
}
```

# What’s the impact of this bug/feature?

I'm not sure if this a bug or I'm just missing something from the language docs about code generation. If the latter, please, let me know where I can find the info about code generation rules.

---

P.S. If there is anything else I can add, please, let me know :)

**Comment by HT154** [comment]
This looks like expected behavior to me.

In the first example without the type annotation, the `server` property in your module has type `Any` (which you happened to have assigned an `HttpServer` to). Because the golang codegen operates based on the types for module/class fields and not the types of assigned values, the emitted go struct accepts `any` for `Server`.

This may be a little surprising if you're accustomed to modern languages that do type inference (eg. Swift). In Swift, `let server = HttpServer()` yields an immutable variable `server` with type `HttpServer`, not `Any`.

In Pkl, it is idiomatic to let type inference happen the other direction, by declaring the type of the property and using a bare `new` when instantiating the declared type:
```pkl
server: HttpServer = new {
  port = 7000
}
```

This practice is covered in more detail in the style guide: https://pkl-lang.org/main/current/style-guide/index.html

**Comment by gsom95** [comment]
> In the first example without the type annotation, the server property in your module has type Any (which you happened to > have assigned an HttpServer to). Because the golang codegen operates based on the types for module/class fields and > not the types of assigned values, the emitted go struct accepts any for Server.
> 
> This may be a little surprising if you're accustomed to modern languages that do type inference (eg. Swift). In Swift, `let server = HttpServer()` yields an immutable variable `server` with type `HttpServer`, not `Any`.

Indeed, this is a little bit confusing, but as you've said it [was covered in the style guide](https://pkl-lang.org/main/current/style-guide/index.html#objects-with-new). 

Thank you @HT154!
